version: "3"
services:
  grafana:
    image: grafana/grafana:9.3.6
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data/:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_data/:/prometheus/
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--web.enable-admin-api --storage.tsdb.retention.time=790d --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.enable-lifecycle"

  solar-exporter:
    image: solar-exporter
    ports:
      - "9942:9942"
    environment:
      DEYE_IP: 192.168.2.15
      DEYE_USER: admin
      DEYE_PASSWORD: admin
