global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 120s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'solar-exporter'
    scrape_timeout: 90s
    scrape_interval: 90s
    static_configs:
     - targets: ['solar-exporter:9942']
